# -*- coding: utf-8 -*-
"""jpgToVideo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pPUD1MM58uaBQURIyemcoOL8roPp0XAr
"""

import cv2
import os

def frames_to_video(frames_folder, output_path, fps):
    # 获取帧文件夹中的所有图像文件
    frame_files = sorted(os.listdir(frames_folder))
    frame_files = [file for file in frame_files if file.endswith('.jpg') or file.endswith('.png')]

    # 从第一帧读取图像，获取图像尺寸
    first_frame = cv2.imread(os.path.join(frames_folder, frame_files[0]))
    height, width, channels = first_frame.shape

    # 创建视频编码器
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    video_writer = cv2.VideoWriter(output_path, fourcc, fps, (width, height))

    # 逐帧写入视频
    for frame_file in frame_files:
        frame_path = os.path.join(frames_folder, frame_file)
        frame = cv2.imread(frame_path)
        video_writer.write(frame)

    # 释放资源
    video_writer.release()


# 使用示例
# frames_folder = './/output_ray'  # 包含图像帧的文件夹路径
# output_path = './video/video.mp4'  # 输出视频的文件路径
# fps = 30  # 视频的帧率

# frames_to_video(frames_folder, output_path, fps)

for fold in os.listdir('./train_data_pic'):
    if not os.path.isdir('video'):
        os.mkdir('video')
    output_path = './video/'+fold+'.mp4'
    frames_to_video('./train_data_pic/'+fold, output_path, fps=30)
